version: "3.0"

services:
  kafka-cluster:
    image: landoop/fast-data-dev
    environment:
      ADV_HOST: 127.0.0.1
      RUNTESTS: 0
      FORWARDLOGS: 0
      SAMPLEDATA: 0
    ports:
      - 2182:2182 #zookeeper
      - 3030:3030 # landoop ui
      - 8091-8093:8081-8083 #rest proxy, schema registry, kafkaconnect
      - 9581-9585:9581-9585 #jmx ports
      - 9092:9092 #kafka broker